environment_version: 1
credentials:
- type: aws
  id: zqpMlFW88BllfB
  description: 'aws read-only '
  access_key_id: AWS_ACCESS_KEY_ID
  secret_access_key: AWS_SECRET_ACCESS_KEY
  region: AWS_DEFAULT_REGION
- type: api-key
  id: JuK8bSIRrPD6a6
  description: Codeocean API (read)
  key: API_KEY
  secret: API_SECRET
